name:                binsert
version:             0.1.0.0
github:              "lgastako/binsert"
license:             BSD3
author:              "John Evans"
maintainer:          "lgastako@gmail.coms"
copyright:           "2020 John Evans"

extra-source-files:
- README.md
- ChangeLog.md

synopsis:            Insert a line in a file via binary insert
category:            File

description:         README at <https://github.com/lgastako/binsert#readme>

dependencies:
- base >= 4.7 && < 5
- directory

executables:
  binsert:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
